Thu Mar 31 23:44:25 CEST 2016 : Apache Derby Network Server - 10.11.1.2 - (1629631) démarré et prêt à accepter les connexions sur le port 1527
----------------------------------------------------------------
Thu Mar 31 23:44:26 CEST 2016:
Amorçage de Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631) : instance a816c00e-0153-cea2-712c-000057706e44 
dans le répertoire de base de données C:\Users\Antoine\Documents\INSA\3IF\DASI\NETBEANS WP\B3421\DB_Collectif avec le chargeur de classe sun.misc.Launcher$AppClassLoader@5e2de80c
Chargé de file:/C:/Program%20Files/Java/jdk1.8.0_60/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_60-b27
user.dir=C:\Program Files\Java\jdk1.8.0_60\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\Antoine\Documents\INSA\3IF\DASI\NETBEANS WP\B3421
Chargeur de classe de la base de données démarré - derby.database.classpath = ''
Thu Mar 31 23:44:27 CEST 2016 Thread[DRDAConnThread_2,5,main] (XID = 45823), (SESSIONID = 0), (DATABASE = DB_Collectif), (DRDAID = {1}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Echec de l'authentification de la connexion. Cause : Authentification non valide..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Echec de l'authentification de la connexion. Cause : Authentification non valide..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR 08004: Echec de l'authentification de la connexion. Cause : Authentification non valide..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Thu Mar 31 23:44:27 CEST 2016 Thread[DRDAConnThread_2,5,main] (DATABASE = DB_Collectif), (DRDAID = {1}), Echec de l'authentification de la connexion. Cause : Authentification non valide..
----------------------------------------------------------------
Thu Mar 31 23:45:11 CEST 2016 : fermeture du moteur Derby
----------------------------------------------------------------
Thu Mar 31 23:45:11 CEST 2016:
Fermeture de l'instance a816c00e-0153-cea2-712c-000057706e44 sur le répertoire de base de données C:\Users\Antoine\Documents\INSA\3IF\DASI\NETBEANS WP\B3421\DB_Collectif avec le chargeur de classe sun.misc.Launcher$AppClassLoader@5e2de80c 
